sprint 8
Yandex-Practicum/go-db-sql-query-test pull request #1
Opened 2024-01-11 21:27 UTC by searcheroflulz

2024-01-13 00:30 UTC, robotomize requested changes
В целом задание сделано правильно, есть небольшие мелочи, чтобы привести все проверки в соответствие с заданием. Также написал часть улучшений по читаемости в некоторых параметрах и мелкий момент на будущее или если станет скучно ждать следующий таск.
Что нужно точно поправить
- Поправьте необязательны проверки в тестах
- Единый интерфейс подключение к БД

2024-01-13 00:30 UTC, robotomize commented on main_test.go
> +	db, err := sql.Open("sqlite", "demo.db")
Оки, работает да, если будет скучно ждать новый материал почитайте про MainTest и как можно вынести создание подключение к БД в отдельный сетап, чтобы не создавать несколько раз

2024-01-13 00:30 UTC, robotomize commented on main_test.go
> +		t.Fatal("empty fio")
В задании указано, что если какие-либо из полей не пустые, то тест не должен завершится и это про все проверки ниже

2024-01-13 00:30 UTC, robotomize commented on main_test.go
> +		t.Error("Unequal IDs")
Лучше писать чуть более информативно в будущем, например что-то в этом духе t.Errorf("client id wrong, want: %d, got: %d", clientID, client.ID) чтобы сразу видеть какие параметры не совпадают и тд

2024-01-13 00:30 UTC, robotomize commented on main_test.go
> +		fmt.Println(err)
В предыдущем тесте по другому обрабатываете ошибку. Лучше в одном стиле это делать, через t.Fatal в данном случае будет корректно, так как мы все равно ничего дальше сделать не сможем

2024-01-13 00:30 UTC, robotomize commented on main_test.go
> +		t.Fatal("not empty ID")
Тут также в задании указано, что если какие-то поля не пустые тест не должен завершится. Это нужно делать, чтобы проверить все кейсы за раз

2024-01-13 00:30 UTC, robotomize commented on main_test.go
> +		t.Fatal(err)
Тут все корректно в целом

2024-01-13 00:30 UTC, robotomize commented on main_test.go
> +		t.Fatal("not equal clients")
Эти проверки также должны быть не фатальными

2024-01-13 10:04 UTC, searcheroflulz commented on main_test.go
> +		t.Fatal("empty fio")
привет! спасибо большое за правки. такой вопрос - как сделать так, чтобы тест не завершился? разве t.Fatal сразу не завершит наш тест? или надо написать t.Fail() или что-то в этом роде? заранее спасибо за ответ!

2024-01-13 13:16 UTC, robotomize commented on main_test.go
> +		t.Fatal("empty fio")
Для этого подойдет t.Errorf или t.Error

2024-01-14 03:15 UTC, robotomize requested changes
Привет! Еще немного прпавок. Основые это Errorf, все остальное в целом не обязательно.
Не заметил еще самую важну вещь, перенесите PR в свой репозиторий

2024-01-14 03:15 UTC, robotomize commented on main_test.go
> +		fmt.Println(err)
Тут нужно завершить работу черещ loo.Fatal или os.Exit

2024-01-14 03:15 UTC, robotomize commented on main_test.go
> +	mainDB.db.Close()
Лучше сделать defer db.Close() сразу после инициализации выше

2024-01-14 03:15 UTC, robotomize commented on main_test.go
> +		t.Fatalf("client id wrong, want: %d, got: %d", clientID, client.ID)
Тут также лучше сделать Errorf потому что это не критичная проверка. По логике еще лчше сначала на пустоту проверять, потом на конкретные кейсы

2024-01-14 03:15 UTC, robotomize commented on main_test.go
> +		t.Fatalf("client id wrong, want: 0, got: %d", client.ID)
Тут также Errorf в этих проверках ниже

2024-01-14 08:24 UTC, searcheroflulz commented on main_test.go
> +	mainDB.db.Close()
я просто вычитал, что os.Exit не гарантирует вызовы defer функций, поэтому решил подстраховаться

2024-01-14 08:31 UTC, robotomize commented on main_test.go
> +	mainDB.db.Close()
Тогда лучше return и перед этим errorf

2024-01-14 22:42 UTC, closed without merging